version: '3.4'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    hostname: localhost
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
